mxmz.getDialogNagi1En = function() {
    return {
        'Good stars, stranger.':'Good stars, stranger.',
        'Can you tell me about this place?':'Can you tell me about this place?',
        'This place is calling "Shards". It is Our Sanctuary. The Good One save us all here.':'This place is calling "Shards". It is Our Sanctuary. The Good One save us all here.',
        'The Good One? Who is it?':'The Good One? Who is it?',
        'He is our Saver.':'He is our Saver.', 
        'He is Pillar of our home':'He is Pillar of our home',
        'He is our Saver.':'He is our Saver.', 
        'He is Pillar of our home':'He is Pillar of our home',
        'He is the one, who does not care about any life.':'He is the one, who does not care about any life.',
        'Sanctuary?':'Sanctuary?',
        'We all lost our homes.':'We all lost our homes.',
        'We are hiding here':'We are hiding here',
        'We are no where to go.':'We are no where to go.',
        'I have more qestions.':'I have more qestions.',
        'Ask.':'Ask.', 
        'Go on':'Go on', 
        'I am glad to answer.':'I am glad to answer.',
        'Tell me about yourself.':'Tell me about yourself.',
        'I am an orphant. Like others.':'I am an orphant. Like others.', 
        'I came here from far away. Like others.':'I came here from far away. Like others.',
        'I living in shards because I no where to go.':'I living in shards because I no where to go.',
        'I will die soon. I wonna sex.':'I will die soon. I wonna sex.',
        'Are you junkie?':'Are you junkie?', 
        'Are you frik?':'Are you frik?', 
        'Fuck off!':'Fuck off!',
        'Never mind.':'Never mind.',
        'Ok.':'Ok.', 
        'As you wish.':'As you wish.', 
        'Come back any time.':'Come back any time.'        
    }
}