mxmz.en_translate =
    {
        'max.dead': 'Max is dead. Hail to the Max! Press Enter.',

        'crash.landing': 'Crash landing',
        'ash.beach': 'Ash beach',
        'stone.circle': 'Stone circle',
        'snake.rift': 'Snake\'s rift',
        'last.sign': 'Last sign',
        'boulder.lair': 'Boulder\'s lair',
        'gray.wasteland': 'Gray wasteland',
        'temple.of.the.dead': 'Temple of the dead',
        'way.to.shadows': 'Way to shadows',
        'tomb.of.the.pagon': 'Tomb of the pagon',
        'here.is.no.loot': 'Here is no loot',
        'cold.path': 'Cold path',
        'beginning.of.everything': 'Beginning of everything',
        'dreams.forever': 'Dreams forever',
        'heart.of.deep': 'Heart of deep',
        'veins.of.the.deep': 'Veins of the deep',
        'lets.cream.you.are.maniacs': 'Let\'s scream: "You are maniacs!"',
        'silent.sands': 'Silent sands',
        'hell.dunes': 'Hell dunes',
        'scorpions.trail': 'Scorpions\'s trail',
        'jins.trap': 'Jins\'s trap',
        'so.just.silica': 'So, just silica',
        'red.rock': 'Red rock',
        'sultry.place': 'Sultry place',
        'lets.ride.with.girls': 'Let\'s ride with girls',
        'cactus.garden': 'Cactus garden',
        'uncharted.roads': 'Uncharted roads',
        'emerald.grove': 'Emerald grove',
        'outskirts': 'Outskirts',
        'wood.goblin.ravine': 'Wood goblin\'s ravine',
        'within.the.woods': 'Within the woods',
        'lets.read.a.book': 'Let\'s read a book',

        'hand.translate': 'Bare knuckle',
        'hand.translate.descr.translate': 'Just hands',
        'weapon.shotgun.translate': 'Shotgun',
        'weapon.shotgun.descr.translate': 'Nice weapon against small aggressive liveforms.',
        'weapon.wasp-gun.translate': 'Waspgun',
        'weapon.wasp-gun.descr.translate': 'Alien weapon, firing a swarm of hyperion wasps',
        'ammo.shells.translate': 'Shells',
        'ammo.shells.descr.translate': 'Standart shells for shotgun.',
        'ammo.wasps.translate': 'Desert wasps',
        'ammo.wasps.descr.translate': 'Jar with desert hyperion wasps',
        'ammo.poison-wasps.translate': 'Swapm Wasps',
        'ammo.poison-wasps.descr.translate': 'Jar with poison swamp hyperion wasps',            
        'ammo.powered-shells.translate': 'Powered shells',
        'ammo.powered-shells.descr.translate': 'Heavy shells for shotgun.',
        'artifact.clone-module.translate': 'Clone module',
        'artifact.clone-module.descr.translate': 'Device to reproduce adult human',

        'resource.clone.translate': 'Clone',
        'resource.clone.descr.translate': 'Human\'s embryo for reproduce adult human in clone module',
        'resource.small-medkit.translate': 'Pills',
        'resource.small-medkit.descr.translate': 'Complex pills with analgesic, antipyretic and antiseptic effect.',
        'resource.medkit.translate': 'Medkit',
        'resource.medkit.descr.translate': 'First aid kit with bandages, iodine and brilliant green. Plus pills.',
        'resource.big-medkit.translate': 'Medpack',
        'resource.big-medkit.descr.translate': 'Regeneration ointment, syringe with adrenaline, flexible nanoarmband, a universal antidote. And, of course, pills.',

        'element.bioplasma.translate': 'Bioplasma',
        'element.bioplasma.descr.translate': 'Simple element bioplasma',
        'element.petrorit.translate': 'Petrorit',
        'element.petrorit.descr.translate': 'Simple element petrorit',
        'element.plutonius.translate': 'Plutonius',
        'element.plutonius.descr.translate': 'Simple element plutonius',
        'element.organoid.translate': 'Organoid',
        'element.organoid.descr.translate': 'Simple element organoid',
        'element.hyperquartz.translate': 'Hyperquartz',
        'element.hyperquartz.descr.translate': 'Simple element hyperquartz',
        'element.dark-matter.translate': 'Dark matter',
        'element.dark-matter.descr.translate': 'Simple element dark matter',            
        'element.kikis.translate': 'Kikis',
        'element.kikis.descr.translate': 'Simple element kikis',
        'element.obsidian.translate': 'Obsidian',
        'element.obsidian.descr.translate': 'Simple element obsidian',
        'element.diamona.translate': 'Diamona',
        'element.diamona.descr.translate': 'Simple element diamona',

        'key.mud-key.translate': 'Mud key',
        'key.mud-key.descr.translate': 'Stupid key of mud. WTF?',

        'resource.shit.translate': 'Healing shit',
        'resource.shit.descr.translate': 'It is said that if you eat this shit healing or even smear, healing comes immediately',

        'npc.tumo.guy': 'Tumo',
        'npc.nagi.guy': 'Nagi',
        'salt.stone.village': 'Salt Stone Village'

    }