mxmz.ru_translate =
        {
            'max.dead': 'Макс умер. Да зравствует Макс! Жми Enter.',
    
            'crash.landing': 'Аварийная посадка',
            'ash.beach': 'Пляж из пепла',
            'stone.circle': 'Каменный круг',
            'snake.rift': 'Змеиная расщелина',
            'last.sign': 'Последний знак',
            'boulder.lair': 'Логово валунов',
            'gray.wasteland': 'Серая пустошь',
            'temple.of.the.dead': 'Храм мертвых',
            'way.to.shadows': 'Путь к теням',
            'tomb.of.the.pagon': 'Гробница язычника',
            'here.is.no.loot': 'Здесь нет добычи',
            'cold.path': 'Холодная тропа',
            'beginning.of.everything': 'Начало всего',
            'dreams.forever': 'Сны навсегда',
            'heart.of.deep': 'Сердце глубины',
            'veins.of.the.deep': 'Вены глубины',
            'lets.cream.you.are.maniacs': 'Давай покричим: "Вы, маньяки!"',
            'silent.sands': 'Тихие пески',
            'hell.dunes': 'Адские дюны',
            'scorpions.trail': 'Тропа скорпионов',
            'jins.trap': 'Западня джинов',
            'so.just.silica': 'Короче, тупо оксид кремния',
            'red.rock': 'Красная скала',
            'sultry.place': 'Знойное место',
            'lets.ride.with.girls': 'Давай проедемся с девушками',
            'cactus.garden': 'Сад кактусов',
            'uncharted.roads': 'Неведомые дорожки',
            'emerald.grove': 'Изумрудная роща',
            'outskirts': 'Опушка',
            'wood.goblin.ravine': 'Овраг леших',
            'within.the.woods': 'В лесах',
            'lets.read.a.book': 'Давай почитаем книжку',
            
            'hand.translate': 'Голые кулаки',
            'hand.translate.descr.translate': 'Просто руки',            
            'weapon.shotgun.translate': 'Дробовик',
            'weapon.shotgun.descr.translate': 'Неплохое оружие против небольших агресствных форм жизни.',
            'weapon.wasp-gun.translate': 'Осамёт',
            'weapon.wasp-gun.descr.translate': 'Инопланетное оружие, стреляющее роем гиперионских ос',
            'ammo.shells.translate': 'Патроны',
            'ammo.shells.descr.translate': 'Стандартные патроны для дробовика.',
            'ammo.wasps.translate': 'Пустынные Осы',
            'ammo.wasps.descr.translate': 'Банка с пустынными гиперионскими осами',
            'ammo.poison-wasps.translate': 'Болотные Осы',
            'ammo.poison-wasps.descr.translate': 'Банка с ядовитыми болотными гиперионскими осами',            
            'ammo.powered-shells.translate': 'Усиленные патроны',
            'ammo.powered-shells.descr.translate': 'Патроны с утяжеленной картечью для дробовика.',
            'artifact.clone-module.translate': 'Клон-модуль',
            'artifact.clone-module.descr.translate': 'Устройство для воспроизводства взрослых людей',
            
            'resource.clone.translate': 'Клон',
            'resource.clone.descr.translate': 'Человеческий эмбрион для воссоздания взрослого человека в клон-модуле',            
            'resource.small-medkit.translate': 'Таблетки',
            'resource.small-medkit.descr.translate': 'Комплексные пилюли с обезболивающим, жаропонижающим и антибиотическим действием',
            'resource.medkit.translate': 'Аптечка',
            'resource.medkit.descr.translate': 'Набор первой помощи с бинтами, йодом и зеленкой. Плюс пилюли.',
            'resource.big-medkit.translate': 'Походный медблок',
            'resource.big-medkit.descr.translate': 'Регенерацинные мази, шприц с адреналином, эластичные наноповязки, универсальный антидот. И, конечно же, пилюли.',            
            
            'element.bioplasma.translate': 'Биоплазма',
            'element.bioplasma.descr.translate': 'Простейший элемент биоплазма',
            'element.petrorit.translate': 'Петрорит',
            'element.petrorit.descr.translate': 'Простейший элемент петрорит',
            'element.plutonius.translate': 'Плутониус',
            'element.plutonius.descr.translate': 'Простейший элемент плутониус',
            'element.organoid.translate': 'Органоид',
            'element.organoid.descr.translate': 'Простейший элемент органоид',
            'element.hyperquartz.translate': 'Гиперкварц',
            'element.hyperquartz.descr.translate': 'Простейший элемент гиперкварц',
            'element.dark-matter.translate': 'Тёмная материя',
            'element.dark-matter.descr.translate': 'Простейший элемент тёмная материя',
            'element.kikis.translate': 'Кикис',
            'element.kikis.descr.translate': 'Простейший элемент кикис',
            'element.obsidian.translate': 'Обсидиан',
            'element.obsidian.descr.translate': 'Простейший элемент обсидиан',
            'element.diamona.translate': 'Диамона',
            'element.diamona.descr.translate': 'Простейший элемент диамона',
            
            'key.mud-key.translate': 'Крязевой ключ',
            'key.mud-key.descr.translate': 'Дурацкий ключ из грязи. КаХу?',
            
            'resource.shit.translate': 'Целебное говно',
            'resource.shit.descr.translate': 'Говорят, что если състь это целебное говно или хотя бы обмазаться, исцеление придет незамедлительно'
        }